version: "3.9"
services:
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4560:4510-4560"  # external services port range
      - "8001:8080"            # only required for Pro
      - "443:443"              # LocalStack HTTPS Gateway (required for Pro)
      - "4571:4571"            # elasticsearch service
    environment:
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse  # To use Docker for Lambda execution
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - DNS_RESOLVE_IP=192.168.25.226
    networks:
      ls:
        ipv4_address: 192.168.25.226
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket into the container

networks:
  ls:
    name: ls
    ipam:
      config:
        - subnet: 192.168.25.224/27